### PR TITLE
Add carthage support

### PR DESCRIPTION
**Pull request by Beniamiiin**

### CODE REVIEW

**Comment by Beniamiiin** [comment]
Guys, are you gonna review it?

**Comment by Beniamiiin** [comment]
Guys, after the last updating carthage can't build the library. What did you add except Lottie dependency?

**Comment by pavel-antonov-idnow** [comment]
Hi @Beniamiiin

**Comment by Beniamiiin** [comment]
Hi @pavel-antonov-idnow.
1. I execute `carthage update --platform iOS --cache-builds` to build all dependencies of idnow sdk.
2. I execute `carthage build --no-skip-current --platform iOS --cache-build` to build idnowsdk framework.

You can try to clone my [fork](https://github.com/Beniamiiin/de.idnow.ios), checkout to `carthage-support` branch and do the above steps and you will get the same error.

P.S. Till the one of the lastest update I could successfully build IDnowSDK framework via Carthage, but currently it's impossible.

**Comment by pavel-antonov-idnow** [comment]
yes we faced the same issues with cocoapods sometime ago but manage to fix that. I'll check your fork

**Comment by Beniamiiin** [comment]
Can you tell me please how did you fix it? Maybe it'll help me to fix it this issue.

**Comment by pavel-antonov-idnow** [comment]
@Beniamiiin  upgrade the version of cocoapods to the latest one resolved absolutely the same issue with `pod spec lint --verbose --allow-warnings` command

**Comment by Beniamiiin** [comment]
@pavel-antonov-idnow, unfortunately, it can't help me with my issue, but I'll try to solve this problem. And I'd like to ask you to help me too :)

**Comment by Beniamiiin** [comment]
Hi, @pavel-antonov-idnow. I tried to clone this repository and run your sample app but I faced a lot of [errors](https://monosnap.com/file/tqU14iJgwTxPbPdKQJ5lvE8gUP0qPj).

**Comment by aare-undo-idnow** [comment]
Carthage and even Swift Package support is now, finally, in the works. However, closing this pull request because at this point it's unmergable (leaving branch for reference)

**Pull request closed without merging**
